changelog:
  categories:
    - title: 💥 Breaking changes
      labels:
        - breaking-change
    - title: ✨ New features
      labels:
        - enhancement
    - title: ⚡️Improvements
      labels:
        - improvement
        - documentation
    - title: 🎨 Other changes
      labels:
        - "*"
