# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Combadge

nav:
  - index.md
  - core-concepts.md
  - Support:
      - Protocols:
          - support/http.md
          - support/rest.md
          - support/soap.md
      - Backends:
          - support/httpx.md
          - support/zeep.md
  - Extending: []

theme:
  icon:
    repo: "fontawesome/brands/github"
    logo: "material/radio-handheld"
  name: material
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green
      accent: green
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: green
      accent: green

plugins:
  - autorefs
  - git-revision-date-localized:
      enable_creation_date: false
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_toc_entry: false
            show_signature_annotations: true
            separate_signature: true
            show_bases: false
            merge_init_into_class: false
            members_order: "source"
  - search:
      lang: en
  - social

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

repo_url: https://github.com/kpn/combadge

extra:
  social:
    - icon: material/github
      link: https://github.com/kpn
      name: KPN on GitHub
    - icon: material/office-building
      link: https://jobs.kpn.com/
      name: Working at KPN

copyright: Copyright &copy; 2023 Koninklijke KPN N.V.

site_url: "https://kpn.github.io/combadge"

watch:
  - "combadge"
